[package]
name = "joy"
version = "0.1.0"
authors = ["Gosick"]
edition = "2018"

[dependencies]
time = "0.2.2"
bitflags = "1.2.1"
sdl2 = { version = "0.33.0", features = ["bundled"] }
structopt = { version = "0.3.7", default-features = false }
blip_buf = "0.1.4"
